site:
  title: Antora Demo Site
  # the 404 page and sitemap files only get generated when the url property is set
  url: http://edufs.edu.htl-leonding.ac.at/~t.stuetz/antora
  start_page: quarkus-lecture-notes::index.adoc
content:
  sources:
  - url: https://github.com/htl-leonding/antora-demo-content-1.git
    branches: master
    start_path: asciidocs
    # setting edit_url to false disables the Edit this Page link for any page that originates from this repository
    # the same thing can be achieved by adding empty credentials (i.e., @) in front of the domain in the URL
    #edit_url: false
  - url: https://github.com/htl-leonding/antora-demo-content-2.git
    branches: master
    start_path: asciidocs
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
asciidoc:
  attributes:
    sectanchors: true
    plantuml-server-url: http://www.plantuml.com/plantuml
    plantuml-fetch-diagram: true
    imagesoutdir: temp_image/
output:
  dir: dist/
